[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]

[build-dependencies]
# Pinned so `cargo update` bumps don't cause breakage
cc = "=1.2.0"


[patch.crates-io]
compiler_builtins = { git = "https://github.com/tgross35/compiler-builtins.git", rev = "feb90fb20aca20be0968fe9450b934e50a36a41d" }
